# Generated by Django 5.1.3 on 2024-12-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='esc50metadata',
            name='esc10',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='esc50metadata',
            name='src_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='esc50metadata',
            name='take',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
